---
version: "2.1"
services:
  homeassistant:
    image: lscr.io/linuxserver/homeassistant:latest
    container_name: homeassistant
    network_mode: host
    environment:
      - PUID=1001
      - PGID=100
      - TZ=Europe/London
    volumes:
      - /SDD/appdata/homeassistant:/config
    ports:
      - 8123:8123 #optional
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    restart: unless-stopped
