---
version: "2"
services:
  homer:
    image: b4bz/homer
    container_name: homer
    volumes:
      - /SDD/appdata/homer/assets/:/www/assets
    ports:
      - 1234:8080
    user: 1001:100 # default
    environment:
      - INIT_ASSETS=1 # default
