version: '2'
services:
  hyper-hdr:
    container_name: hyper-hdr
    hostname: hyper-hdr
    image: nocturno/hyper-hdr:latest
    network_mode: host
    devices:
      - /dev/video0:/dev/video0
      - /dev/spidev0.0:/dev/spidev0.0
    environment:
      - TZ=Europe/London
      - PGID=1001
      - PUID=100
    ports:
      - 8090:8090
      - 19444:19444
      - 19445:19445
    volumes:
      - /SDD/appdata/hyperhdr:/config
    restart: unless-stopped
