---
version: "2.1"
services:
  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - AUTO_UPDATE=true #optional
      - RUN_OPTS= #optional
    volumes:
      - ${APPDATA}/jackett:/config
      - ${MEDIA}/downloads:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped