---
version: "2"
services:
  qbittorrentvpn:
    image: chrisjohnson00/qbittorrent-openvpn:latest
    container_name: qbittorrentvpn
    privileged: true   
    environment:
      - VPN_USERNAME=${VPN_USERNAME}
      - VPN_PASSWORD=${VPN_PASSWORD}
      - PUID=${PUID}
      - PGID=${PGID}
      - WEBUI_PORT_ENV=8080 #optional
      - INCOMING_PORT_ENV=8999 #optional
      - VPN_ENABLED=yes
      - LAN_NETWORK=192.168.1.0/24
      - NAME_SERVERS=103.86.96.100,103.86.99.100
    ports:
      - 8080:8080
      - 8999:8999
      - 8999:8999/udp
    volumes:
      - ${APPDATA}/qbittorrent:/config
      - ${MEDIA}/downloads:/downloads
    restart: unless-stopped